export const screeningReportSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    company: { type: "string" },
    deckTitle: { type: "string" },
    sector: { type: "string" },
    stage: { type: "string" },
    analysisDate: { type: "string" },
    verdict: {
      type: "string",
      enum: ["建议推进", "有条件推进", "暂缓", "不建议推进"],
    },
    confidence: { type: "string", enum: ["高", "中", "低"] },
    oneLineConclusion: { type: "string" },
    technical: { $ref: "#/$defs/dimension" },
    market: { $ref: "#/$defs/dimension" },
    capital: { $ref: "#/$defs/dimension" },
    keyClaims: {
      type: "array",
      items: { $ref: "#/$defs/claim" },
    },
    marketReality: {
      type: "array",
      items: { type: "string" },
    },
    capitalReturn: {
      type: "array",
      items: { type: "string" },
    },
    diligenceAsks: {
      type: "array",
      items: { type: "string" },
    },
    decisionGates: {
      type: "array",
      items: { type: "string" },
    },
    sources: {
      type: "array",
      items: { $ref: "#/$defs/source" },
    },
    limitations: {
      type: "array",
      items: { type: "string" },
    },
  },
  required: [
    "company",
    "deckTitle",
    "sector",
    "stage",
    "analysisDate",
    "verdict",
    "confidence",
    "oneLineConclusion",
    "technical",
    "market",
    "capital",
    "keyClaims",
    "marketReality",
    "capitalReturn",
    "diligenceAsks",
    "decisionGates",
    "sources",
    "limitations",
  ],
  $defs: {
    dimension: {
      type: "object",
      additionalProperties: false,
      properties: {
        score: {
          type: "integer",
          description: "0–100 的初筛风险调整分，必须在该区间内",
        },
        judgment: { type: "string" },
        evidence: { type: "array", items: { type: "string" } },
        gaps: { type: "array", items: { type: "string" } },
      },
      required: ["score", "judgment", "evidence", "gaps"],
    },
    claim: {
      type: "object",
      additionalProperties: false,
      properties: {
        category: {
          type: "string",
          enum: ["技术", "监管", "市场", "资本"],
        },
        claim: { type: "string" },
        slideRef: { type: "string" },
        evidenceStatus: {
          type: "string",
          enum: ["已核实", "部分支持", "冲突", "未找到"],
        },
        evidence: { type: "array", items: { type: "string" } },
        implication: { type: "string" },
        risk: { type: "string", enum: ["高", "中", "低"] },
      },
      required: [
        "category",
        "claim",
        "slideRef",
        "evidenceStatus",
        "evidence",
        "implication",
        "risk",
      ],
    },
    source: {
      type: "object",
      additionalProperties: false,
      properties: {
        title: { type: "string" },
        url: { type: "string" },
        publisher: { type: "string" },
        accessedAt: { type: "string" },
      },
      required: ["title", "url", "publisher", "accessedAt"],
    },
  },
} as const;
